# Generated by Django 6.0.3 on 2026-03-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('tls_version', models.CharField(blank=True, max_length=50)),
                ('cipher_suite', models.CharField(blank=True, max_length=255)),
                ('key_exchange', models.CharField(blank=True, max_length=255)),
                ('pqc_status', models.CharField(default='Unknown', max_length=50)),
                ('risk_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
