# Generated by Django 6.0.3 on 2026-03-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='key_exchange',
        ),
        migrations.AddField(
            model_name='asset',
            name='issuer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='key_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='signature_algorithm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='subject',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='pqc_status',
            field=models.CharField(max_length=50),
        ),
    ]
