# Generated by Django 6.0.3 on 2026-03-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_remove_asset_key_exchange_asset_issuer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='days_to_expiry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='key_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='protocol',
            field=models.CharField(default='TLS', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='scan_status',
            field=models.CharField(default='Success', max_length=50),
        ),
    ]
