# Generated by Django 6.0.3 on 2026-03-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_asset_days_to_expiry_asset_key_type_asset_protocol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='alert_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='alert_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='scan_type',
            field=models.CharField(default='single', max_length=50),
        ),
    ]
